version: "3.9"

services:
  java_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: postgresql://ep-calm-term-a4jnquak-pooler.us-east-1.aws.neon.tech:5432/neondb
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_0u3PzNdSriKj
    networks:
      - java_network


volumes:
  postgres-data:

networks:
  java_network:

